/*  PiggyVault i18n Engine  */
(function(){
'use strict';
const SUPPORTED=['it','en','de','es','fr','pt','zh','ja','ko','ru','hi'];
const DEFAULT='en';
let _lang=DEFAULT;
const _dict={};

/* ── Italian (master) ── */
_dict.it={
"common.back":"← Indietro","common.close":"Chiudi","common.cancel":"Annulla","common.confirm":"Conferma","common.save":"Salva","common.copy":"Copia","common.copied":"Copiato!","common.loading":"Caricamento...","common.or":"oppure","common.later":"Più tardi","common.activate_now":"Attiva ora","common.private":"🔒 Privato","common.free":"🆓 Gratuito","common.works_offline":"📱 Funziona offline",
"splash.tagline":"Il salvadanaio che non si rompe","splash.msg1":"Connessione alla blockchain…","splash.msg2":"Preparazione crittografia…","splash.msg3":"Caricamento wallet SDK…","splash.msg4":"Inizializzazione interfaccia…","splash.msg5":"Verifica sicurezza dati…","splash.msg6":"Configurazione smart contract…","splash.msg7":"Sincronizzazione rete Polygon…","splash.msg8":"Quasi pronto…",
"welcome.tagline":"Il salvadanaio che nemmeno tu puoi rompere.","welcome.desc":"Metti da parte i tuoi soldi e bloccali fino alla data che scegli. Nessuno può toccarli prima — nemmeno tu.","welcome.login_passkey":"🔐 Accedi con Face ID / Touch ID","welcome.login_email":"📧 Accedi con Email","welcome.create_manual":"✨ Crea manualmente (12 parole)","welcome.restore_seed":"🔑 Ho già le 12 parole segrete",
"login.title":"Accedi con la tua email","login.desc":"Ti mandiamo un codice di verifica. Nessuna password da ricordare.","login.placeholder":"es. mario@email.com","login.send_code":"Invia codice →","login.footer":"Creeremo automaticamente un portafoglio sicuro collegato alla tua email. Nessuna frase segreta da salvare.",
"otp.title":"Inserisci il codice","otp.sent_to":"Abbiamo inviato un codice a:","otp.placeholder":"Codice a 6 cifre","otp.verify":"Verifica →","otp.resend":"Non hai ricevuto il codice? Reinvia","otp.back":"← Cambia email",
"loading.title":"Stiamo preparando tutto","loading.msg":"Creazione del tuo portafoglio sicuro in corso...",
"seed.title":"🔑 Le tue parole segrete","seed.screen_title":"🔑 Le tue 12 parole segrete","seed.desc":"Queste parole sono la combinazione della tua cassaforte. Sono l'unico modo per recuperare i tuoi risparmi se cambi telefono.","seed.warn_title":"📝 Scrivile su carta adesso","seed.warn_desc":"Copiala su un foglio e mettilo al sicuro. Se perdi queste parole, nessuno potrà aiutarti a recuperare i soldi — nemmeno noi.","seed.copy":"📋 Copia le parole","seed.done":"✅ Fatto, le ho salvate","seed.modal_desc":"Non mostrare queste parole a nessuno. Chi le ha può accedere ai tuoi soldi.",
"pin.create_title":"Crea il tuo PIN","pin.create_desc":"Scegli 6 numeri per aprire la tua app velocemente.","pin.label":"6 cifre","pin.confirm_title":"Conferma PIN","pin.confirm_desc":"Inserisci il PIN per continuare",
"unlock.title":"Bentornato! 👋","unlock.desc":"Inserisci il tuo PIN per entrare","unlock.label":"PIN","unlock.biometric":"🔓 Usa Face ID / Biometria","unlock.forgot":"PIN dimenticato? Recupera con le 12 parole →",
"restore.title":"Recupera il tuo account","restore.desc":"Inserisci le 12 parole segrete che avevi salvato, nell'ordine corretto.","restore.btn":"🔓 Recupera i miei risparmi",
"home.available":"Saldo disponibile","home.recharge":"Ricarica","home.gas":"Gas","home.gas_spent":"Speso","home.gas_convert":"Converti","home.total_locked":"Totale Bloccato","home.next_unlock":"Prossimo sblocco","home.beginner_step":"Primo passo","home.beginner_text":"Il tuo saldo è 0. Aggiungi soldi per iniziare.","home.beginner_desc":"Ti apriamo una pagina già pronta: tu scegli solo l'importo e paghi.","home.beginner_btn":"Aggiungi soldi","home.install_title":"Esperienza app","home.install_text":"Installa PiggyVault sulla schermata Home","home.install_ios":"Safari → Condividi → Aggiungi a Home.","home.install_android":"Installala ora per aprirla come una vera app, a schermo pieno.","home.install_android_manual":"Menu ⋮ del browser → Installa app.","home.install_btn":"Installa app","home.donate_title":"Supporta PiggyVault","home.donate_label":"Open source & gratuito","home.donate_send":"Invia donazione",
"tab.home":"Home","tab.vaults":"Salvadanai","tab.stats":"Statistiche","tab.settings":"Impostazioni",
"vaults.title":"I Tuoi Salvadanai","vaults.new":"+ Nuovo","vaults.empty_title":"Nessun salvadanaio ancora","vaults.empty_desc":"Crea il primo e inizia a mettere da parte!","vaults.filter_all":"Tutti","vaults.filter_active":"Attivi","vaults.filter_unlocked":"Sbloccati",
"stats.progress_title":"I Tuoi Progressi","stats.progress_desc":"Come stanno crescendo i tuoi risparmi","stats.total_deposited":"Totale Depositato","stats.deposit_count":"N. Versamenti","stats.avg_per_vault":"Media per Salvadanaio","stats.active_vaults":"Salvadanai Attivi","stats.timeline":"Timeline Sblocchi","stats.no_timeline":"Nessun salvadanaio con data di sblocco futura.",
"settings.title":"Impostazioni","settings.email_account":"Account Email","settings.email_desc":"Portafoglio integrato — le chiavi sono protette e recuperabili via email.","settings.currency":"Valuta di visualizzazione","settings.currency_desc":"Saldo, gas e totale bloccato saranno mostrati in questa valuta.","settings.address":"Il tuo indirizzo","settings.address_desc":"Come un IBAN, ma per le crypto. Puoi condividerlo.","settings.passkey_title":"Accesso rapido con Passkey","settings.passkey_btn":"Attiva Passkey (Face ID / Touch ID)","settings.passkey_desc":"Registra una passkey per accedere più velocemente.","settings.seed_btn":"Mostra le 12 parole segrete","settings.quick_access":"Accesso rapido","settings.biometric_off":"Biometria non attiva su questo dispositivo.","settings.biometric_enable":"Attiva Face ID / Biometria","settings.biometric_disable":"Disattiva","settings.movements":"Vedi i miei movimenti","settings.dev":"Per sviluppatori","settings.source":"Codice sorgente (GitHub)","settings.ipfs":"Versione permanente (IPFS)","settings.delete":"Esci e cancella da questo dispositivo","settings.language":"Lingua",
"newvault.title":"Nuovo Salvadanaio","newvault.subtitle":"Crea il tuo spazio di risparmio","newvault.icon_name":"Scegli un'icona e un nome","newvault.name_label":"Nome del salvadanaio","newvault.unlock_title":"Quando puoi riaprirlo?","newvault.mode_date":"A una data","newvault.mode_target":"A una cifra","newvault.mode_first":"Il primo","newvault.mode_both":"Entrambi","newvault.mode_hint_date":"Si apre quando arriva la data che scegli.","newvault.mode_hint_target":"Si apre quando raggiungi la cifra obiettivo.","newvault.mode_hint_first":"Si apre appena una delle due condizioni si avvera.","newvault.mode_hint_both":"Si apre solo quando ENTRAMBE le condizioni sono soddisfatte.","newvault.target_label":"Quanto vuoi raggiungere?","newvault.date_label":"Non aprire prima del","newvault.tz_label":"Fuso orario: il tuo locale","newvault.currency_strategy":"Valuta e strategia","newvault.currency_label":"Valuta","newvault.strategy_base":"Caveau Base","newvault.strategy_base_desc":"0% — Nessun rischio","newvault.strategy_aave":"Caveau Interessi","newvault.strategy_aave_desc":"~3-7% annuo via Aave","newvault.stable_note":"Valute stabili: 1 USDC ≈ 1$, 1 EURe ≈ 1€, 1 ZCHF ≈ 1 CHF","newvault.create_btn":"Crea il mio salvadanaio",
"detail.progress":"Progresso","detail.target":"Obiettivo:","detail.rename":"Rinomina","detail.rename_label":"Nuovo nome","detail.rename_save":"Salva on-chain","detail.rename_fee":"Costa una piccola commissione in MATIC","detail.deposit_title":"Aggiungi soldi","detail.deposit_matic":"⛽ Servono pochi centesimi per la commissione.","detail.deposit_matic_fix":"Risolvilo automaticamente","detail.amount_label":"Importo","detail.auto_convert":"💱 Se il tuo saldo è in una valuta diversa, la conversione avviene automaticamente.","detail.lock_btn":"Blocca nel salvadanaio","detail.unlocked":"Salvadanaio sbloccato!","detail.unlocked_desc":"I fondi sono pronti per essere ritirati nel tuo wallet.","detail.withdraw_btn":"Ritira i fondi nel wallet","detail.withdrawn":"Fondi già ritirati nel wallet.","detail.tx_history":"Storico versamenti","detail.panic":"Voglio ritirare prima","detail.delete_vault":"Elimina salvadanaio","detail.send_direct":"Hai già le crypto? Inviale direttamente",
"onramp.title":"Ricarica","onramp.subtitle":"Quanto vuoi mettere nel tuo salvadanaio?","onramp.amount_label":"Altro importo","onramp.continue":"Continua →","onramp.change_amount":"Cambia importo","onramp.your_address":"Il tuo indirizzo","onramp.copy_address":"Copia indirizzo","onramp.choose_provider":"Scegli dove continuare. Le pagine si aprono gia' compilate con il tuo indirizzo.","onramp.recommended":"consigliato","onramp.sepa":"Bonifico SEPA","onramp.mtp_methods":"Carta · SEPA · Apple Pay · Google Pay","onramp.card":"Carta","onramp.self_send":"Invio diretto dal tuo wallet","onramp.self_send_title":"Invio diretto al tuo wallet","onramp.self_send_desc":"Se hai già delle crypto su un exchange o su un altro wallet, puoi inviarle direttamente qui.","onramp.your_addr_polygon":"Il tuo indirizzo (rete Polygon)","onramp.back_methods":"Torna ai metodi","onramp.check_balance":"Ho inviato — Controlla saldo","onramp.check_paid":"Ho pagato, controlla saldo","onramp.recharge_about":"Ricarica circa {amount}€ al tuo saldo","onramp.choose_how_much":"Scegli quanto vuoi ricaricare.",
"lock.title":"🔒 Conferma il blocco","lock.vault":"Salvadanaio","lock.amount":"Quanto blocchi","lock.opens_on":"Si apre il","lock.target":"Obiettivo","lock.type":"Tipo","lock.account":"Account","lock.balance":"Saldo disponibile","lock.warn_title":"⚠️ Non si può annullare","lock.warn_desc":"Una volta confermato, questi soldi saranno bloccati fino alla scadenza. Nessuno potrà ritirarli prima — nemmeno tu.","lock.execute":"🔒 Blocca i soldi","lock.think":"Ci devo pensare",
"crosschain.title":"🌐 Deposita da un'altra valuta","crosschain.choose":"Scegli la crypto da inviare","crosschain.send":"Invii","crosschain.receive":"Ricevi","crosschain.send_to":"Manda a questo indirizzo","crosschain.copy":"📋 Copia indirizzo","crosschain.waiting":"⏳ In attesa del deposito...",
"panic.title":"Non si può aprire!","panic.line1":"Questo è esattamente il punto.","panic.line2":"I tuoi soldi sono bloccati e nessuno può toccarli prima della scadenza — nemmeno tu, nemmeno noi.","panic.back":"Ho capito, torno indietro",
"passkey.title":"Attiva Face ID / Touch ID","passkey.desc":"Vuoi accedere più velocemente la prossima volta? Attiva la passkey biometrica e non dovrai più inserire email e codice.",
"biometric.title":"Vuoi attivare Face ID / Biometria?","biometric.desc":"Così puoi sbloccare l'app più velocemente senza digitare il PIN ogni volta.",
"onboard.title":"Prima di iniziare","onboard.your_addr_polygon":"Il tuo indirizzo wallet (rete Polygon)","onboard.copy":"Copia indirizzo","onboard.check":"Ho inviato — Verifica il saldo","onboard.skip":"Lo farò dopo",
"pin.confirm_title":"Conferma il PIN","pin.confirm_desc":"Reinserisci le 6 cifre per confermare.","pin.mismatch":"I PIN non corrispondono. Riprova.","pin.wrong":"PIN errato. Riprova.","pin.new_title":"Imposta Nuovo PIN","pin.new_desc":"Scegli un nuovo PIN di 6 cifre.",
"restore.forgot_title":"Recupera con le parole segrete","restore.forgot_desc":"Inserisci le 12 parole per reimpostare il PIN.","restore.error_empty":"Inserisci tutte e 12 le parole segrete.","restore.error_wrong":"Le parole non sono corrette. Controlla e riprova.",
"common.vault":"Salvadanaio","common.copied_btn":"✅ Copiata!","common.copied_clipboard":"Copiato! Cancella subito dagli appunti dopo averla salvata.","common.error":"Errore",
"badge.text":"Versione: {version} • Aggiornata: {updated}",
"gas.recharge":"⚠️ Ricarica","gas.low":"⚡ Basso","gas.ok":"✓ OK",
"notify.vault_open":"🔓 {icon} {name} è aperto!","notify.vault_ready":"Il tuo salvadanaio è pronto! Puoi finalmente ritirare i soldi.",
"onramp.min_amount":"Minimo 10€","onramp.checking":"⏳ Controllo saldo in corso...","onramp.no_deposit":"⏳ Nessun deposito rilevato. Aspetta qualche minuto e riprova.","onramp.refresh_error":"❌ Non riesco a verificare ora. Riprova tra poco.","onramp.share_title":"Il mio indirizzo PiggyVault",
"onramp.mtp_notice_title":"Mt Pelerin — Info KYC","onramp.mtp_no_kyc":"Bonifico SEPA fino a ~€950/mese: <strong>senza verifica identità</strong> (solo telefono + email)","onramp.mtp_kyc":"Carta, Apple/Google Pay o oltre ~€950/mese: <strong>verifica identità richiesta</strong>","onramp.mtp_fees":"Bonifico fino a €499: gratuito · Oltre €500: 1.3% commissione",
"dash.days":"{d} giorni","dash.all_open":"Tutti aperti","dash.no_vaults":"nessun salvadanaio",
"filter.all":"Tutti","filter.active":"Attivi","filter.unlocked":"Sbloccati","filter.withdrawn":"Ritirati","filter.aave":"Aave",
"card.withdrawn":"Ritirato","card.to_withdraw":"Da ritirare",
"vault.error_name":"Inserisci un nome.","vault.error_currency":"Seleziona una valuta.","vault.error_wallet":"❌ Wallet non connesso. Accedi prima.","vault.error_target":"Inserisci una cifra obiettivo valida.","vault.error_date":"Seleziona una data di sblocco.","vault.error_date_invalid":"Data non valida.","vault.error_date_future":"La data deve essere nel futuro.","vault.error_matic":"⛽ Serve più MATIC. Hai solo {bal} POL — servono almeno 0.002 per creare un salvadanaio.","vault.creating":"⏳ Transazione in corso sulla blockchain...","vault.timeout":"Timeout: la transazione non ha risposto entro 60 secondi.","vault.confirming":"⏳ Attendi la conferma...","vault.btn_creating":"⏳ Creazione on-chain...",
"detail.open":"APERTO!","detail.hours":"{h} ore","detail.few_minutes":"Pochi minuti","detail.months_days":"{mo} mesi e {dd}g","detail.days":"{d} giorni","detail.to_reach":"{amount} {currency} da raggiungere","detail.locked":"BLOCCATO","detail.no_tx":"Nessun versamento ancora","detail.condition_date_met":"Data raggiunta ({date})","detail.condition_date_pending":"{date} — {d} giorni","detail.condition_or":"OPPURE","detail.condition_and":"E","detail.condition_target_met":"Obiettivo raggiunto ({current}/{target})","detail.aave_title":"Caveau con Interessi (Aave)","detail.aave_current":"Valore attuale:","detail.aave_interest":"Interessi maturati:","detail.aave_note":"I rendimenti sono variabili e dipendono dal mercato Aave.","detail.panic_date":"Torna il {date}.","detail.panic_target":"Raggiungi {target} {currency} per sbloccare.","detail.unsupported":"⚠️ {currency} non esiste su Polygon. Questo salvadanaio non può ricevere depositi. Crea un nuovo salvadanaio con USDC, DAI, USDT, EURe o ZCHF.",
"withdraw.in_progress":"⏳ Ritiro in corso...","withdraw.checking":"🔍 Verifico stato sulla blockchain...","withdraw.tx_sent":"⏳ Transazione inviata, attendo conferma...","withdraw.success":"✅ Fondi ritirati nel wallet!","withdraw.wallet_error":"Wallet non connesso","withdraw.not_unlocked":"Il salvadanaio non è ancora sbloccato sulla blockchain. Riprova tra qualche minuto.","withdraw.already_done":"I fondi sono già stati ritirati.","withdraw.not_owner":"Non sei il proprietario di questo salvadanaio.","withdraw.no_funds":"Non ci sono fondi da ritirare.",
"rename.saving":"⏳ Salvataggio...","rename.tx_pending":"Transazione in corso sulla blockchain...","rename.confirming":"Attendi la conferma...","rename.success":"✅ Nome aggiornato on-chain!","rename.matic_error":"⛽ Serve MATIC per la commissione. Hai solo {bal} MATIC.",
"delete.confirm":"Vuoi davvero eliminare \"{name}\"?","delete.confirm_tw":"SEI SICURO? Verrai disconnesso dal tuo account su questo dispositivo.","delete.confirm_classic":"SEI SICURO? Tutti i dati saranno rimossi da questo dispositivo. Assicurati di aver salvato le 12 parole segrete!",
"bio.card_title":"Face ID / Biometria","bio.card_desc":"Attiva per sbloccare l'app senza digitare il PIN.","bio.card_btn":"Attiva biometria","bio.card_active_title":"Biometria attiva","bio.card_active_desc":"Puoi sbloccare l'app con Face ID / impronta digitale.","bio.card_disable":"Disattiva biometria",
"bio.card_title":"Face ID / Biometria","bio.card_desc":"Attiva per sbloccare l'app senza digitare il PIN.","bio.card_btn":"Attiva biometria","bio.card_active_title":"Biometria attiva","bio.card_active_desc":"Puoi sbloccare l'app con Face ID / impronta digitale.","bio.card_disable":"Disattiva biometria","biometric.not_supported":"Biometria non supportata su questo dispositivo/browser.","biometric.unlock_first":"Per sicurezza, prima sblocca una volta con PIN e poi attiva la biometria.","biometric.activated":"Biometria attivata con successo.","biometric.failed":"Non sono riuscito ad attivare la biometria. Riprova.","biometric.status_unsupported":"Biometria non supportata su questo browser/dispositivo.","biometric.status_active":"Biometria attiva. Puoi sbloccare rapidamente con Face ID / impronta.","biometric.status_inactive":"Biometria non attiva su questo dispositivo.","biometric.cancelled":"Autenticazione biometrica annullata o fallita.",
"chart.linear":"Obiettivo lineare","chart.real":"Risparmio reale",
"deposit.error_amount":"Inserisci un importo valido.","deposit.not_connected":"Non sei connesso. Riapri l'app.",
"donate.sending":"🔄 Invio in corso...","donate.confirming":"⏳ Attendo conferma...","donate.success":"✅ Grazie per la donazione! 💚","donate.confirm_title":"☕ Conferma donazione","donate.invalid":"Inserisci una cifra valida.","donate.login_required":"Devi prima fare il login.",
"lock.convert_lock":"💱 Converti e Blocca","lock.lock_money":"🔒 Blocca i soldi","lock.available":"Disponibile: {amount} {currency}","lock.unavailable":"Saldo non disponibile","lock.unavailable_conn":"Saldo non disponibile (controlla connessione)","lock.not_connected":"❌ Non sei connesso. Riapri l'app e riprova.","lock.need_pol":"⛽ Serve più POL. Hai solo {bal} POL — servono almeno {min}.","lock.not_on_chain":"❌ Questo salvadanaio non è ancora sulla blockchain. Ricrealo.","lock.step1_auth":"1/2 — Autorizzazione in corso...","lock.step1_confirm":"1/2 — Attendi conferma approve...","lock.step2_aave":"2/2 — Deposito su Aave in corso...","lock.step2_lock":"2/2 — Blocco dei soldi in corso...","lock.step2_almost":"2/2 — Quasi fatto...","lock.success_aave":"✅ Soldi bloccati con interessi su Aave!","lock.success_base":"✅ Soldi bloccati con successo!","lock.retry":"🔒 Riprova","lock.done":"✅ Fatto!","lock.deposit_with":"📩 Deposita con {label}",
"lock.swap_step1":"1/4 — Calcolo conversione...","lock.swap_step2":"2/4 — Autorizzazione in corso...","lock.swap_step3":"3/4 — Conversione in corso...","lock.swap_step4_aave":"4/4 — Deposito su Aave...","lock.swap_step4_lock":"4/4 — Blocco dei soldi...","lock.swap_success":"✅ Convertito e bloccato! {srcAmt} {src} → {destAmt} {dest}","lock.src_not_found":"❌ Token sorgente non trovato.","lock.need_pol_swap":"⛽ Serve più POL. Hai solo {bal} POL — servono almeno 0.005 per una conversione+blocco.",
"cc.creating":"Creazione in corso...","cc.creating_order":"⏳ Creazione ordine...","cc.error":"Errore SideShift","cc.waiting":"⏳ In attesa del deposito...","cc.processing":"⚙️ Conversione in corso...","cc.review":"🔍 In revisione...","cc.completed":"✅ Completato! {amount} {currency} ricevuti.","cc.expired":"❌ Ordine scaduto","cc.refunded":"❌ Ordine rimborsato",
"onboard.checking":"🔄 Controllo in corso...","onboard.found":"✅ Trovati {bal} POL — Sei pronto!","onboard.not_arrived":"⏳ Saldo POL: {bal} — Non ancora arrivato. Riprova tra qualche secondo.","onboard.check_error":"❌ Errore nel controllo. Riprova.",
"pol.getting_quote":"🔄 Ottengo quotazione...","pol.preparing":"🔄 Preparo transazione...","pol.sending":"🔄 Invio transazione...","pol.confirming":"⏳ Attendi conferma...","pol.nothing":"Niente da convertire","pol.gas_preparing":"⛽ Preparazione commissioni in corso...","pol.gas_ready":"✅ Commissioni pronte! Ora puoi continuare.",
"auth.loading":"⏳ Caricamento...","auth.sdk_unavailable":"SDK non disponibile. Controlla la connessione e riprova.","auth.email_invalid":"Inserisci un indirizzo email valido.","auth.sending":"⏳ Invio in corso...","auth.send_error":"Errore nell'invio del codice. Riprova tra qualche secondo.","auth.send_code":"Invia codice →","auth.otp_invalid":"Inserisci il codice ricevuto via email.","auth.verifying":"⏳ Verifica in corso...","auth.otp_wrong":"Codice errato. Controlla e riprova.","auth.otp_error":"Errore nella verifica. Riprova.","auth.verify_btn":"Verifica →","auth.resent":"✅ Codice reinviato!","auth.resend_error":"Impossibile reinviare il codice. Riprova.","auth.success":"Autenticazione riuscita. Preparazione portafoglio...","auth.connecting":"Connessione al portafoglio Polygon...","auth.ready":"Tutto pronto!","auth.error":"Errore. Riprova.",
"passkey.auth_required":"Devi essere autenticato per attivare la Passkey.","passkey.enrolling":"⏳ Registrazione...","passkey.activated":"✅ Passkey attivata! Potrai accedere con Face ID / Touch ID.","passkey.error":"Errore nell'attivazione della Passkey: {msg}","passkey.active_label":"✅ Passkey attiva","passkey.active_desc":"Puoi accedere con Face ID / Touch ID dalla schermata di benvenuto.","passkey.register_desc":"Registra una passkey per accedere più velocemente.","passkey.login_error":"Errore nell'accesso con Passkey: {msg}","passkey.sdk_unavailable":"SDK non disponibile. Riprova.","passkey.login_as":"🔐 Accedi come {email}",
"pay.more":"Altre valute ▾","pay.less":"Meno valute ▴","pay.lock":"🔒 Blocca",
"unlock_mode.date":"A una data","unlock_mode.target":"A una cifra","unlock_mode.first":"Il primo dei due","unlock_mode.both":"Entrambi","unlock_mode.hint_date":"Si apre quando arriva la data che scegli.","unlock_mode.hint_target":"Si apre quando raggiungi la cifra che vuoi.","unlock_mode.hint_first":"Si apre quando arriva la data OPPURE raggiungi la cifra.","unlock_mode.hint_both":"Si apre solo quando ENTRAMBE le condizioni sono soddisfatte.","newvault.quote_unavail":"Quote non disponibile","newvault.step1_title":"Identità","newvault.step2_title":"Sblocco","newvault.step3_title":"Condizioni","newvault.step3_sub":"Imposta data e/o obiettivo","newvault.step4_title":"Valuta e strategia","newvault.step4_sub":"Scegli come custodire i fondi","newvault.strategy_base":"Caveau Base","newvault.strategy_base_desc":"0% — Nessun rischio","newvault.strategy_aave":"Caveau Interessi","newvault.strategy_aave_desc":"~3-7% annuo via Aave","newvault.aave_disclaimer":"⚠️ I fondi vengono depositati nel protocollo Aave (DeFi) per generare interessi variabili. PiggyVault è solo un'interfaccia — i rendimenti non sono garantiti.","newvault.noaave_warning":"ℹ️ Questa valuta non è supportata da Aave su Polygon. Solo il Caveau Base è disponibile.","newvault.stablecoin_hint":"1 USDC ≈ 1$, 1 EURe ≈ 1€, 1 ZCHF ≈ 1 CHF","newvault.tz_hint":"Fuso orario: il tuo locale","settings.language_label":"Lingua dell'app",
"lock_screen.title":"PiggyVault","lock_screen.desc":"Sblocca per continuare","lock_screen.use_bio":"Sblocca con Face ID","lock_screen.use_pin":"Sblocca con PIN","lock_screen.relogin":"Accedi di nuovo con email",
"bio.not_supported":"Biometria non supportata su questo browser/dispositivo.","bio.active":"Biometria attiva. Puoi sbloccare rapidamente con Face ID / impronta.","bio.not_active":"Biometria non attiva su questo dispositivo.","bio.unlock_first":"Per sicurezza, prima sblocca una volta con PIN e poi attiva la biometria.","bio.enabled":"Biometria attivata con successo.","bio.failed":"Non sono riuscito ad attivare la biometria. Riprova.","bio.confirm_disable":"Sei sicuro di voler disattivare la biometria?\n\nSenza biometria il tuo account sarà meno protetto.",
"deposit.error_not_connected":"Non sei connesso. Riapri l'app.","deposit.available":"Disponibile: {bal} {currency}","deposit.balance_unavailable":"Saldo non disponibile","deposit.convert_and_lock":"💱 Converti e Blocca","deposit.deposit_with":"📩 Deposita con {coin}","deposit.lock_btn":"🔒 Blocca","deposit.less_currencies":"Meno valute ▴","deposit.more_currencies":"Altre valute ▾","deposit.need_more_pol":"⛽ Serve più POL. Hai solo {bal} POL — servono almeno {min}.","deposit.need_more_pol_swap":"⛽ Serve più POL. Hai solo {bal} POL — servono almeno 0.005 per una conversione+blocco.","deposit.not_on_chain":"❌ Questo salvadanaio non è ancora sulla blockchain. Ricrealo.","deposit.src_not_found":"❌ Token sorgente non trovato.","deposit.step_approve":"1/2 — Autorizzazione in corso...","deposit.step_approve_wait":"1/2 — Attendi conferma approve...","deposit.step_lock":"2/2 — Blocco dei soldi in corso...","deposit.step_aave":"2/2 — Deposito su Aave in corso...","deposit.step_almost":"2/2 — Quasi fatto...","deposit.success":"✅ Soldi bloccati con successo!","deposit.success_aave":"✅ Soldi bloccati con interessi su Aave!","deposit.swap_step1":"1/4 — Calcolo conversione...","deposit.swap_step2":"2/4 — Autorizzazione in corso...","deposit.swap_step3":"3/4 — Conversione in corso...","deposit.swap_step4":"4/4 — Blocco dei soldi...","deposit.swap_step4_aave":"4/4 — Deposito su Aave...","deposit.swap_success":"✅ Convertito e bloccato! {srcAmt} {src} → {destAmt} {dest}","deposit.unsupported_currency":"⚠️ {currency} non esiste su Polygon.",
"convert.nothing":"Niente da convertire","convert.quoting":"🔄 Ottengo quotazione...","convert.preparing":"🔄 Preparo transazione...","convert.sending":"🔄 Invio transazione...","convert.confirming":"⏳ Attendi conferma...","convert.quote_unavailable":"Quote non disponibile",
"automatic.preparing":"⛽ Preparazione commissioni in corso...","automatic.ready":"✅ Commissioni pronte! Ora puoi continuare.","automatic.error":"❌ Errore: {error}",
"cc.error_sideshift":"Errore SideShift","cc.converting":"⚙️ Conversione in corso...","cc.reviewing":"🔍 In revisione...",
"common.done":"✅ Fatto!","common.retry":"🔒 Riprova","common.days":"{d} giorni","common.no_date":"Nessuna data",
"onboard.found_pol":"✅ Trovati {bal} POL — Sei pronto!",
"onramp.stablecoin_received":"Ricevuti {amount} stablecoin!","onramp.pol_converting":"Ricevuti POL. Conversione in corso...","onramp.converting":"🔄 Conversione in corso...","onramp.conversion_done":"✅ Conversione completata!","onramp.conversion_failed":"❌ Conversione fallita.","onramp.pol_received_ok":"✅ Ricevuti POL!","onramp.pol_connect_convert":"Ricevuti POL. Connettiti per convertire l'eccesso in saldo.",
"detail.aave_disclaimer":"I rendimenti sono variabili e dipendono dal mercato Aave.","detail.aave_earned":"Interessi maturati:","detail.and":"E","detail.or":"OPPURE","detail.date_reached":"Data raggiunta ({date})","detail.target_reached":"Obiettivo raggiunto ({current}/{target})",
"donate.confirm_body":"Vuoi inviare {amount} {token} come donazione?","donate.error":"❌ Errore nella donazione.","donate.error_amount":"Inserisci una cifra valida.","donate.error_login":"Devi prima fare il login.","donate.token_unavailable":"Token non disponibile per la donazione.",
"rename.need_matic":"⛽ Serve MATIC per la commissione. Hai solo {bal} MATIC.","rename.save_btn":"💾 Salva on-chain",
"seed.copied_alert":"Copiato! Cancella subito dagli appunti dopo averla salvata.","seed.not_found":"Nessuna frase segreta trovata su questo dispositivo.",
"settings.confirm_delete":"Vuoi davvero eliminare \"{name}\"?","settings.confirm_delete_full":"SEI SICURO? Tutti i dati saranno rimossi da questo dispositivo.",
"tw.sdk_unavailable":"SDK non disponibile. Controlla la connessione e riprova.","tw.invalid_email":"Inserisci un indirizzo email valido.","tw.sending":"⏳ Invio in corso...","tw.send_error":"Errore nell'invio del codice. Riprova tra qualche secondo.","tw.send_code":"Invia codice →","tw.enter_code":"Inserisci il codice ricevuto via email.","tw.verifying":"⏳ Verifica in corso...","tw.wrong_code":"Codice errato. Controlla e riprova.","tw.verify_error":"Errore nella verifica. Riprova.","tw.verify_btn":"Verifica →","tw.code_resent":"✅ Codice reinviato!","tw.resend_error":"Impossibile reinviare il codice. Riprova.","tw.auth_success":"Autenticazione riuscita. Preparazione portafoglio...","tw.all_ready":"Tutto pronto!","tw.error_retry":"Errore. Riprova.","tw.must_auth_passkey":"Devi essere autenticato per attivare la Passkey.","tw.registering":"⏳ Registrazione...","tw.passkey_activated":"✅ Passkey attivata! Potrai accedere con Face ID / Touch ID.","tw.enroll_passkey_btn":"🔐 Attiva Passkey (Face ID / Touch ID)","tw.passkey_error":"Errore nell'attivazione della Passkey: {error}","tw.login_passkey_btn":"🔐 Accedi con Face ID / Touch ID","tw.passkey_login_error":"Errore nell'accesso con Passkey: {error}","tw.passkey_active":"✅ Passkey attiva","tw.passkey_active_desc":"Puoi accedere con Face ID / Touch ID dalla schermata di benvenuto.","tw.passkey_enroll_desc":"Registra una passkey per accedere più velocemente.","tw.login_as":"🔐 Accedi come {email}",
"withdraw.btn":"💰 Ritira i fondi nel wallet","withdraw.err_already":"I fondi sono già stati ritirati.","withdraw.err_no_funds":"Non ci sono fondi da ritirare.","withdraw.err_not_owner":"Non sei il proprietario di questo salvadanaio.","withdraw.err_not_unlocked":"Il salvadanaio non è ancora sbloccato sulla blockchain. Riprova tra qualche minuto.","withdraw.not_unlocked_debug":"Il salvadanaio non è ancora sbloccato sulla blockchain.",
"home.btn_topup":"Ricarica","home.btn_withdraw":"Ritira","home.no_withdrawable":"Non ci sono salvadanai pronti per il ritiro al momento.",
"settings.bug_title":"Segnala un bug","settings.bug_desc":"Hai trovato un problema? Descrivilo e lo risolveremo il prima possibile.","settings.bug_subject_ph":"Oggetto","settings.bug_body_ph":"Descrivi il problema...","settings.bug_send":"Invia segnalazione","settings.bug_empty":"Inserisci una descrizione del problema.",
"settings.bank_title":"Dati bancari","settings.bank_desc":"Per velocizzare i ritiri su conto corrente. I dati restano solo sul tuo dispositivo.","settings.bank_name_label":"Nome e Cognome (intestatario)","settings.bank_ok":"✓ Completo","settings.bank_empty":"Non compilato","settings.bank_incomplete":"Incompleto",
"withdraw.title":"Ritira fondi","withdraw.subtitle":"Scegli quanto vuoi ritirare.","withdraw.available":"Saldo disponibile nel wallet","withdraw.total":"Totale","withdraw.how_much":"Quanto vuoi ritirare?","withdraw.all":"Tutto","withdraw.continue":"Continua","withdraw.full_balance":"Intero saldo disponibile","withdraw.exceeds":"Importo superiore al saldo disponibile","withdraw.min_amount":"Importo minimo: $1","withdraw.no_balance":"Non hai fondi nel wallet da ritirare.",
"withdraw.bank_title":"Bonifico bancario (SEPA)","withdraw.bank_desc":"Ricevi euro sul tuo conto corrente","withdraw.bank_fee":"Fino a €499: GRATIS · Oltre: 1.3%","withdraw.wallet_title":"Invia a un altro wallet","withdraw.wallet_desc":"Trasferisci crypto a un indirizzo esterno","withdraw.wallet_fee":"Solo gas fee (~$0.01)","withdraw.info_consolidate":"Se hai token diversi, verranno convertiti automaticamente in USDC prima del ritiro.",
"withdraw.send_to_wallet":"Invia a wallet esterno","withdraw.choose_token":"Seleziona token","withdraw.amount":"Importo","withdraw.dest_address":"Indirizzo destinatario","withdraw.send_warning":"Verifica l'indirizzo! Una volta inviati, i fondi NON sono recuperabili. Assicurati che l'indirizzo sia su rete Polygon.","withdraw.send_confirm":"Conferma invio","withdraw.consolidating":"Conversione token in corso...","withdraw.opening_widget":"Apertura widget di vendita...",
"withdraw.invalid_address":"Indirizzo non valido","withdraw.same_address":"Questo è il tuo stesso indirizzo","withdraw.valid_address":"Valido","withdraw.balance_label":"{balance} {token} disponibili","withdraw.fill_all":"Compila tutti i campi","withdraw.insufficient":"Saldo {token} insufficiente","withdraw.confirm_send":"Inviare {amount} {token} a {addr}?","withdraw.sending":"Invio in corso...","withdraw.confirming_tx":"Conferma transazione...","withdraw.sent_ok":"✓ Invio completato!","withdraw.error":"Errore nel ritiro",
"onramp.mtp_disclaimer":"I pagamenti sono elaborati da Mt Pelerin, un servizio terzo regolamentato. PiggyVault non gestisce, non custodisce e non è responsabile delle transazioni finanziarie. Verifica sempre i dati prima di confermare.",
"onramp.mtp_timing":"I tempi di accredito variano: con KYC completato pochi minuti, senza KYC fino a 24-48h per il primo acquisto. Bonifico SEPA: 1-2 giorni lavorativi.",
"onramp.mtp_kyc_tip":"Consiglio: completa il KYC per sbloccare limiti più alti e ricevere i fondi più velocemente.",
"onramp.mtp_terms_link":"Termini e condizioni Mt Pelerin",
"settings.export_key_btn":"Esporta chiave privata",
"export.title":"🔑 Chiave privata",
"export.loading":"⏳ Recupero chiave...",
"export.warning":"⚠️ Chi ha questa chiave ha accesso ai tuoi fondi. Non condividerla con nessuno!",
"export.tap_reveal":"Tocca per mostrare/nascondere",
"export.copy":"📋 Copia chiave privata",
"export.import_hint":"Puoi importare questa chiave in MetaMask, Rainbow, Rabby o qualsiasi wallet compatibile con Polygon.",
"export.secured_title":"🔒 Chiave protetta da Thirdweb",
"export.secured_desc":"La tua chiave privata è gestita in modo sicuro dall'infrastruttura Thirdweb e non è accessibile dall'app. Questo è un livello di sicurezza extra: nessuna app può rubare le tue chiavi.",
"export.portable_title":"✅ Il tuo wallet è portabile",
"export.portable_desc":"Il tuo indirizzo wallet funziona su qualsiasi dApp compatibile con Polygon. I tuoi fondi non sono bloccati in PiggyVault.",
"export.your_address":"Il tuo indirizzo:",
"export.copy_address":"📋 Copia indirizzo",
"export.how_title":"Come esportare la chiave?",
"export.how_desc":"Accedi con la stessa email su qualsiasi dApp che usa Thirdweb ConnectButton, poi seleziona \"Gestisci Wallet\" → \"Esporta chiave privata\". La chiave è la stessa su ogni piattaforma.",
"export.copied_toast":"Chiave copiata negli appunti",
"export.address_copied_toast":"Indirizzo copiato negli appunti"
};

/* ── Translate helper: returns key from current lang, fallback to IT ── */
window.t=function(key,params){
  var s=(_dict[_lang]&&_dict[_lang][key])||_dict.it[key]||key;
  if(params){Object.keys(params).forEach(function(k){s=s.replace('{'+k+'}',params[k]);});}
  return s;
};

/* ── Apply translations to all [data-i18n] elements ── */
function applyTranslations(){
  document.querySelectorAll('[data-i18n]').forEach(function(el){
    var key=el.getAttribute('data-i18n');
    var val=t(key);
    if(val!==key){
      if(el.tagName==='INPUT'||el.tagName==='TEXTAREA'){
        el.placeholder=val;
      } else if(el.hasAttribute('data-i18n-html')){
        el.innerHTML=val;
      } else {
        el.textContent=val;
      }
    }
  });
  document.documentElement.lang=_lang;
}

/* ── Set language ── */
window.setAppLanguage=function(lang){
  if(SUPPORTED.indexOf(lang)===-1) lang=DEFAULT;
  _lang=lang;
  localStorage.setItem('piggy_lang',lang);
  applyTranslations();
};

/* ── Get current language ── */
window.getAppLanguage=function(){return _lang;};
window.getSupportedLanguages=function(){return SUPPORTED.slice();};

/* ── Language metadata (flags + names) ── */
window.LANG_META={
  it:{flag:"🇮🇹",name:"Italiano"},
  en:{flag:"🇬🇧",name:"English"},
  de:{flag:"🇩🇪",name:"Deutsch"},
  es:{flag:"🇪🇸",name:"Español"},
  fr:{flag:"🇫🇷",name:"Français"},
  pt:{flag:"🇵🇹",name:"Português"},
  zh:{flag:"🇨🇳",name:"中文"},
  ja:{flag:"🇯🇵",name:"日本語"},
  ko:{flag:"🇰🇷",name:"한국어"},
  ru:{flag:"🇷🇺",name:"Русский"},
  hi:{flag:"🇮🇳",name:"हिन्दी"}
};

/* ── Init: load saved language or detect system language ── */
var saved=localStorage.getItem('piggy_lang');
if(saved&&SUPPORTED.indexOf(saved)!==-1){ _lang=saved; }
else{
  var nav=navigator.language||navigator.userLanguage||'';
  var code=nav.split('-')[0].toLowerCase();
  _lang=SUPPORTED.indexOf(code)!==-1?code:DEFAULT;
}
// Expose _dict for adding translations from separate files
window._i18nDict=_dict;
window.applyTranslations=applyTranslations;

})();
