sonar.projectKey=creazionecontenuti-oss_caveau-digitale
sonar.organization=creazionecontenuti-oss
sonar.projectName=PiggyVault (Caveau Digitale)

sonar.sources=.
sonar.inclusions=app.js,i18n.js,sw.js,contracts/**/*.sol
sonar.exclusions=node_modules/**,lib/**,app.min.js,thirdweb-sdk.js,privy-sdk.js,i18n-langs.js,project-export.txt

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
